<?php
namespace App\Http\Controllers\Auth;
use App\Http\Controllers\Controller; use App\Models\LoginOtp; use App\Models\User; use Illuminate\Http\Request; use Illuminate\Support\Facades\Auth; use Illuminate\Support\Facades\Hash; use Illuminate\Support\Facades\Http; use Illuminate\Support\Str;
class OtpLoginController extends Controller {
 public function show(){ return view('auth.login'); }
 public function requestCode(Request $request){ $data=$request->validate(['email'=>'required|email']); $email=strtolower($data['email']); $user=User::where('email',$email)->where('is_active',true)->first(); if(!$user && $email===strtolower((string)env('ADMIN_EMAIL'))){$user=User::create(['name'=>'Dr B','email'=>$email,'password'=>Hash::make(Str::random(40)),'role'=>'admin','is_active'=>true]);} if(!$user)return back()->withErrors(['email'=>'This email is not authorised. Contact the administrator.']); $code=(string)random_int(100000,999999); LoginOtp::where('email',$email)->whereNull('used_at')->update(['used_at'=>now()]); LoginOtp::create(['email'=>$email,'code_hash'=>Hash::make($code),'expires_at'=>now()->addMinutes(10),'request_ip'=>$request->ip()]); $response=Http::withToken(config('services.resend.key'))->post('https://api.resend.com/emails',['from'=>config('services.resend.from_name').' <'.config('services.resend.from_address').'>','to'=>[$email],'subject'=>'Your Klinik Bustari Cash Flow login code','html'=>'<div style="font-family:Arial;padding:24px"><h2>Klinik Bustari Cash Flow</h2><p>Your one-time login code is:</p><div style="font-size:32px;font-weight:700;letter-spacing:8px">'.$code.'</div><p>This code expires in 10 minutes. Do not share it.</p></div>']); if(!$response->successful())return back()->withErrors(['email'=>'We could not send the OTP. Check the Resend configuration.']); session(['otp_email'=>$email]); return redirect()->route('otp.verify')->with('status','A 6-digit code was sent to your email.'); }
 public function showVerify(){ if(!session('otp_email'))return redirect()->route('login'); return view('auth.verify',['email'=>session('otp_email')]); }
 public function verify(Request $request){$data=$request->validate(['code'=>'required|digits:6']);$email=session('otp_email');$otp=LoginOtp::where('email',$email)->whereNull('used_at')->where('expires_at','>',now())->latest()->first();if(!$otp||$otp->attempts>=5||!Hash::check($data['code'],$otp->code_hash)){if($otp)$otp->increment('attempts');return back()->withErrors(['code'=>'Invalid or expired code.']);}$otp->update(['used_at'=>now()]);$user=User::where('email',$email)->where('is_active',true)->firstOrFail();$user->update(['last_login_at'=>now(),'email_verified_at'=>$user->email_verified_at??now()]);Auth::login($user,true);$request->session()->regenerate();$request->session()->forget('otp_email');return redirect()->intended(route('dashboard'));}
 public function logout(Request $request){Auth::logout();$request->session()->invalidate();$request->session()->regenerateToken();return redirect()->route('login');}
}
